name: 릴리즈 노트 자동 작성

on:
  push:
    branches:
      - main

jobs:
  create_notion_page:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.5
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44.3.0

      - name: Get commit info
        id: commit-info
        run: |
          echo "commits=${{ steps.changed-files.outputs.all_modified_files }}" >> $GITHUB_OUTPUT

      - name: Create Notion pages
        if: steps.commit-info.outputs.commits != ''
        env:
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
        run: |
          commits=${{ steps.commit-info.outputs.commits }}
          python .github/scripts/main.py "$commits"