name: Github-Jira-Notion Integration

on:
  push:
    branches:
      - main

jobs:
  integration:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Extract Jira ticket number
      id: extract_jira_ticket
      run: |
        commit_message=$(git log -1 --pretty=%B)
        ticket_number=$(echo $commit_message | grep -oE 'JIRA-[0-9]+' | head -1)
        echo "TICKET_NUMBER=$ticket_number" >> "$GITHUB_ENV"

    - name: Extract commit title and summary
      id: extract_commit_info
      run: |
        echo "COMMIT_TITLE=$(git log -1 --pretty=%s)" >> "$GITHUB_ENV"
        echo "COMMIT_SUMMARY=$(git log -1 --pretty=%b)" >> "$GITHUB_ENV"

    - name: Create Notion page
      env:
        NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
        NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
      run: |
        chmod +x .github/scripts/create_notion_page.sh
        .github/scripts/create_notion_page.sh "$TICKET_NUMBER" "$COMMIT_TITLE" "$COMMIT_SUMMARY"
