name: 릴리즈 노트 자동 작성

on:
  push:
    branches:
      - main

jobs:
  create_notion_page:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.5

      - name: Get all commits
        id: get-commits
        run: echo "commits=${{ join(github.event.commits.*.id, ',') }}" >> $GITHUB_OUTPUT

      - name: Debug workspace structure
        run: |
          echo "Workspace structure:"
          tree "$GITHUB_WORKSPACE"

      - name: Create Notion pages
        env:
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
        run: |
          python "$GITHUB_WORKSPACE/.github/scripts/main.py" "${{ steps.get-commits.outputs.commits }}"