name: 릴리즈 노트 자동 작성

on:
  push:
    branches:
      - main

jobs:
  get_commits:
    runs-on: ubuntu-latest
    outputs:
      commits: ${{ steps.get_commits_step.outputs.commits }}
    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: 커밋 목록 가져오기
        id: get_commits_step
        run: |
          commits=$(git log --format=%H ${{ github.event.before }}..${{ github.event.after }})
          echo "commits=$(echo $commits | tr '\n' ' ')" >> $GITHUB_OUTPUT

  create_notion_page:
    needs: get_commits
    if: success() && needs.get_commits.result == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: 노션 페이지 생성
        env:
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
        run: |
          commits=${{ needs.get_commits.outputs.commits }}
          IFS=' ' read -ra commit_array <<< "$commits"
          
          for commit in "${commit_array[@]}"
          do
            echo "Processing commit: $commit"
            git checkout $commit
          
            commit_message=$(git log -1 --pretty=%B)
            ticket_number=$(echo "$commit_message" | grep -oE '[A-Z]+-[0-9]+' | head -1)
            module_names=$(echo "$commit_message" | grep -oE '@[a-zA-Z]+' | tr -d '@' | tr '[:lower:]' '[:upper:]' | tr '\n' ' ')
          
            commit_title=$(git log -1 --pretty=%s | sed -E 's/([A-Z]+-[0-9]+|@[a-zA-Z]+)//g' | sed -E 's/^[[:space:]]*|[[:space:]]*$//g')
            commit_summary=$(git log -1 --pretty=%b | sed -z 's/\n/\\n/g')
          
            chmod +x .github/scripts/read_version.sh
            version=$(.github/scripts/read_version.sh)
          
            if [[ -n "$ticket_number" || -n "$module_names" ]]; then
              chmod +x .github/scripts/create_notion_page.sh
              .github/scripts/create_notion_page.sh "$ticket_number" "$module_names" "$commit_title" "$commit_summary" "$version"
            fi
          
            sleep 1
          done