name: 릴리즈 노트 자동 작성

on:
  push:
    branches:
      - main

jobs:
  create_notion_page:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.5
        with:
          fetch-depth: 0

      - name: Get all commits
        id: get-commits
        run: |
          commits=$(echo '${{ join(github.event.commits.*.id, ',') }}')
          echo "commits=$commits" >> $GITHUB_OUTPUT

      - name: Create Notion pages
        env:
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
        run: |
          python .github/scripts/main.py "${{ steps.get-commits.outputs.commits }}"