name: Github-Notion-Jira Integration

on:
  push:
    branches:
      - main

jobs:
  integration:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Jira 티켓 추출
      id: extract_jira_ticket
      run: |
        commit_message=$(git log -1 --pretty=%B)
        ticket_number=$(echo $commit_message | grep -oE 'JIRA-[0-9]+' | head -1)
        echo "::set-output name=ticket_number::$ticket_number"

    - name: Git 커밋 제목 내용 추출
      id: extract_commit_info
      run: |
        echo "::set-output name=title::$(git log -1 --pretty=%s)"
        echo "::set-output name=summary::$(git log -1 --pretty=%b)"

    - name: Notion 릴리즈 노트 작성
      env:
        NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
        NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
      run: |
        chmod +x .github/scripts/create_notion_page.sh
        .github/scripts/create_notion_page.sh "${{ steps.extract_jira_ticket.outputs.ticket_number }}" "${{ steps.extract_commit_info.outputs.title }}" "${{ steps.extract_commit_info.outputs.summary }}"
